//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_Project1_Part1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string GameName { get; set; }
        public System.DateTime MatchDate { get; set; }
        public int MatchNumber { get; set; }
        public int RoundNumber { get; set; }
        public string FirstTeam { get; set; }
        public string SecondTeam { get; set; }
        public string Winner { get; set; }
        public System.TimeSpan MatchLength { get; set; }
        public int Dragons { get; set; }
        public int Gold { get; set; }
        public string Forfeit { get; set; }
        public string PlayOfTheGame { get; set; }
    }
}
